#! /bin/sh

NAME=nqptp
DAEMON=/usr/bin/$NAME

case "$1" in
    start)
	printf "Starting nqptp: "
	setcap 'cap_net_bind_service=+ep' $DAEMON
	start-stop-daemon -S -q -b --exec $DAEMON
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    stop)
	printf "Stopping nqptp: "
	start-stop-daemon -K -q --exec $DAEMON 
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
    restart)
	echo "Restarting $NAME: "
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0
